// client/components/CommonHome.tsx
import * as React from "react";
import { useQuery, useQueryClient } from "react-query";
import { io } from "socket.io-client";
import { AdminHome } from "./admin/AdminHome";
import { ax, UserContext } from "./App";
import { UserHome } from "./user/UserHome";
import { UserCard } from "./UserCard";

const socket = io();

export const UserColorContext = React.createContext<
    { [key: string]: string }[]
>([]);

export function CommonHome({
    jwt,
    isAdmin,
}: {
    jwt: string;
    isAdmin: boolean;
}) {
    const queryClient = useQueryClient();
    const user = React.useContext(UserContext);
    const { data, isLoading } = useQuery<string>("subject", () =>
        ax
            .get<string>("/hub/subject", { headers: { Authorization: jwt } })
            .then((res) => res.data)
    );

    const { data: usersData, isLoading: loadingUsers } = useQuery(
        "userColor",
        () =>
            ax
                .get("/user/color", { headers: { Authorization: jwt } })
                .then((res) => res.data)
    );

    React.useEffect(() => {
        ax.defaults.headers.common["Authorization"] = jwt;

        socket.emit("token", jwt);

        socket.on("message", (m: string) => {
            console.log(m);
        });

        socket.on("invalidate", (key: string) => {
            queryClient.invalidateQueries(key);
        });

        if (!user?.isAdmin) {
            socket.emit("ping", user?.userId, user?.username);
            setInterval(
                () => socket.emit("ping", user?.userId, user?.username),
                5000
            );
        }
    }, []);

    const home = isAdmin ? (
        <AdminHome />
    ) : (
        <main>
            <UserHome />
        </main>
    );

    if (loadingUsers) {
        return <p>"loading..."</p>;
    }

    return (
        <UserColorContext.Provider value={usersData}>
            <header>
                <h1>#dagensspørsmål</h1>
                {user && <UserCard username={user?.username} />}
            </header>
            <div className="subject">
                <h1>{isLoading ? "loading..." : data}</h1>
            </div>
            {home}
        </UserColorContext.Provider>
    );
}

// client/src/CommonHome.svelte
<script lang="ts">
    import { useQuery } from "@sveltestack/svelte-query";
    import { ax, userColors, user } from "./store";
    import UserCard from "./UserCard.svelte";
    import AdminHome from "./AdminHome.svelte";
    import UserHome from "./UserHome.svelte";

    const subjectQuery = useQuery<string>("subject", () =>
        $ax.get("/hub/subject").then((res) => res.data)
    );

    $ax.get("/user/color").then((res) => ($userColors = res.data));
</script>

<header>
    <h1>#dagensspørsmål</h1>
    <UserCard username={$user.username} />
</header>
<div class="subject">
    <h1>
        {#if $subjectQuery.isLoading}
            "loading..."
        {:else}
            {$subjectQuery.data}
        {/if}
    </h1>
</div>
{#if $user.isAdmin}
    <AdminHome />
{:else}
    <UserHome />
{/if}

<style>
    .subject {
        display: flex;
        justify-content: center;
    }

    .subject h1 {
        z-index: -1;
        margin: 0;
        border-radius: 0 0 10px 10px;
        padding: 0.5em 1em;
        background-color: var(--white-400);
        width: fit-content;
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }
</style>
